/* tslint:disable */
/* eslint-disable */
/**
 * FG Request service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StreamRequest
 */
export interface StreamRequest {
    /**
     * 
     * @type {string}
     * @memberof StreamRequest
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof StreamRequest
     */
    takeOffId?: number;
    /**
     * 
     * @type {string}
     * @memberof StreamRequest
     */
    StreamType?: string;
    /**
     * 
     * @type {string}
     * @memberof StreamRequest
     */
    time?: string;
    /**
     * queue | ready | taken
     * @type {string}
     * @memberof StreamRequest
     */
    status?: string;
}

export function StreamRequestFromJSON(json: any): StreamRequest {
    return StreamRequestFromJSONTyped(json, false);
}

export function StreamRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'takeOffId': !exists(json, 'takeOffId') ? undefined : json['takeOffId'],
        'StreamType': !exists(json, 'StreamType') ? undefined : json['StreamType'],
        'time': !exists(json, 'time') ? undefined : json['time'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function StreamRequestToJSON(value?: StreamRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'takeOffId': value.takeOffId,
        'StreamType': value.StreamType,
        'time': value.time,
        'status': value.status,
    };
}


