/* tslint:disable */
/* eslint-disable */
/**
 * FF Order service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StreamChannel
 */
export interface StreamChannel {
    /**
     * 
     * @type {string}
     * @memberof StreamChannel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof StreamChannel
     */
    geo?: string;
    /**
     * 
     * @type {string}
     * @memberof StreamChannel
     */
    photo?: string;
    /**
     * Stream types that are available to order
     * @type {Array<string>}
     * @memberof StreamChannel
     */
    StreamTypes?: Array<string>;
}

export function StreamChannelFromJSON(json: any): StreamChannel {
    return StreamChannelFromJSONTyped(json, false);
}

export function StreamChannelFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamChannel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'geo': !exists(json, 'geo') ? undefined : json['geo'],
        'photo': !exists(json, 'photo') ? undefined : json['photo'],
        'StreamTypes': !exists(json, 'StreamTypes') ? undefined : json['StreamTypes'],
    };
}

export function StreamChannelToJSON(value?: StreamChannel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'geo': value.geo,
        'photo': value.photo,
        'StreamTypes': value.StreamTypes,
    };
}


