/* tslint:disable */
/* eslint-disable */
/**
 * FP Order service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StreamType
 */
export interface StreamType {
    /**
     * 
     * @type {string}
     * @memberof StreamType
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof StreamType
     */
    name?: string;
}

export function StreamTypeFromJSON(json: any): StreamType {
    return StreamTypeFromJSONTyped(json, false);
}

export function StreamTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function StreamTypeToJSON(value?: StreamType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}


